import Head from 'next/head';
import MainPage from './mainpage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Vote For Me</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainPage />
    </>
  );
}
